/// Cluster management commands

use eyre::Result;
use std::path::PathBuf;

/// Initialize a new cluster
pub async fn init_cluster(cluster_name: String) -> Result<()> {
    println!("🏗️  Creating cluster...");
    
    let malai_home = crate::core::get_malai_home();
    let cluster_dir = malai_home.join("clusters").join(&cluster_name);
    
    // Ensure cluster directory exists
    std::fs::create_dir_all(&cluster_dir)?;
    
    // Generate or read existing cluster manager identity
    let identity_dir = malai_home.join("keys");
    std::fs::create_dir_all(&identity_dir)?;
    
    let identity_file = identity_dir.join("identity.key");
    let (cluster_manager_id52, _cluster_manager_secret) = if identity_file.exists() {
        // Read existing identity
        let secret_key_hex = std::fs::read_to_string(&identity_file)?;
        let secret_key = fastn_id52::SecretKey::from_str(&secret_key_hex.trim())?;
        let id52 = secret_key.id52();
        (id52, secret_key)
    } else {
        // Generate new identity using fastn_id52
        let secret_key = fastn_id52::SecretKey::generate();
        let id52 = secret_key.id52();
        // Save to file
        std::fs::write(&identity_file, secret_key.to_string())?;
        (id52, secret_key)
    };
    
    println!("📝 Generated cluster manager identity: {}", cluster_manager_id52);
    
    // Create basic cluster config  
    let cluster_config = format!(
        r#"# Malai Cluster Configuration
# Generated by: malai cluster init {}
# Cluster Name: {}
# Cluster Manager: {}

[cluster_manager]
id52 = "{}"
cluster_name = "{}"
use_keyring = true

# Add machines to this cluster by editing this file
# Examples:

# Basic machine (accepts remote access)
# [machine.web01]
# id52 = "machine-id52-here"
# allow_from = "*"

# With command aliases
# [machine.web01.command.restart-nginx]
# allow_from = "admins"
# command = "sudo systemctl restart nginx"

# With HTTP services  
# [machine.web01.http.admin]
# port = 8080
# allow_from = "admins"
# secure = false
"#,
        cluster_name,
        cluster_name,
        cluster_manager_id52,
        cluster_manager_id52,
        cluster_name
    );
    
    let config_path = cluster_dir.join("cluster-config.toml");
    std::fs::write(&config_path, cluster_config)?;
    
    println!("✅ Cluster configuration created at: {}", config_path.display());
    println!("Cluster created with ID: {}", cluster_manager_id52);
    println!("Cluster name: {}", cluster_name);
    
    Ok(())
}